"""Create transactions table

Revision ID: a78234ff263b
Revises: 
Create Date: 2025-02-26 21:54:01.363074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78234ff263b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bankaccount', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('transType', sa.String(length=1), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('transactionid', sa.String(length=100), nullable=True),
    sa.Column('transactiontime', sa.String(length=100), nullable=True),
    sa.Column('referencenumber', sa.String(length=100), nullable=True),
    sa.Column('orderId', sa.String(length=19), nullable=True),
    sa.Column('terminalCode', sa.String(length=50), nullable=True),
    sa.Column('subTerminalCode', sa.String(length=50), nullable=True),
    sa.Column('serviceCode', sa.String(length=50), nullable=True),
    sa.Column('urlLink', sa.String(length=255), nullable=True),
    sa.Column('sign', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transactionid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
